### ISSUE TITLE
doesnt check if its installed?

### ISSUE THREAD

**Issue by MACscr** [site24x7/puppet-site24x7#1]
Your class doesn't appear to check to see if the agent is already installed, thus keeps reinstalling itself. =(

**Comment by site24x7-old** [comment]
Hi MACscr,
         We have a check to see if the agent is already installed or not in the exec portion of 'Install Linux Agent'. However once the agent is installed if the script tries to install again it will be prompting for uninstallation of the agent which was installed earlier. Can you share any puppet logs to debug on the same?

**Comment by vmpr** [comment]
Hi, 

it seems, that this not working:

we have already installed the agent at this moment:

then we execute:
puppet agent --test --no-noop

in my opinion, the output says, that it reinstalls the complete environment:

Notice: /Stage[main]/Site24x7::Linuxagent/Exec[remove_tmp_directory]/returns: executed successfully
Notice: site24x7 linux monitoring agent installation completed
Notice: /Stage[main]/Site24x7/Notify[site24x7 linux monitoring agent installation completed]/message: defined 'message' as 'site24x7 linux monitoring agent installation completed'
Notice: Proxy Info  : proxy:3128
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[Proxy Info  : proxy:3128]/message: defined 'message' as 'Proxy Info  : proxy:3128'
Notice: File To Download : Site24x7_Linux_64bit.install
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[File To Download : Site24x7_Linux_64bit.install]/message: defined 'message' as 'File To Download : Site24x7_Linux_64bit.install'
Notice: /Stage[main]/Site24x7::Linuxagent/Exec[Site24x7 Linux Agent]/returns: executed successfully
Notice: /Stage[main]/Site24x7::Linuxagent/File[/tmp/site24x7agent/Linux_Agent.install]/mode: mode changed '0644' to '0755'
Notice: Succesully Completed
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[Succesully Completed]/message: defined 'message' as 'Succesully Completed'
Notice: site24x7 linux monitoring agent installation started
Notice: /Stage[main]/Site24x7/Notify[site24x7 linux monitoring agent installation started]/message: defined 'message' as 'site24x7 linux monitoring agent installation started'
Notice: OS Architecture : x86_64
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[OS Architecture : x86_64]/message: defined 'message' as 'OS Architecture : x86_64'
Notice: DEVICE KEY  : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[DEVICE KEY  : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]/message: defined 'message' as 'DEVICE KEY  : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
Notice: Finished catalog run in 5.41 seconds

Thank you for help!
Ringo

**Comment by site24x7-old** [comment]
Hello Ringo, 

Thank you for writing to us. 

We are analyzing this, please give us some more time and will get back to you with an update as soon as possible. Regards,
Mohammad Rafee
 Site24x7 Team | ZOHO Corp

US: +1 408 352 9117 | UK: +44 203 564 7893

4141 Hacienda Dr, Pleasanton, CA 94588, USA

Site24x7  | Help Guide | Knowledge Base | Blogs | Forums | Demo

If you have any concerns please mail to escalations@site24x7.com

Site24x7 Pre-Meetup Plan - Tell us your Preference

---- On Sat, 15 Oct 2016 00:18:28 +0530 notifications@github.com  wrote ----

**Comment by site24x7** [comment]
Hi ringo,
Thanks for your patience. We have fixed the issue kindly

**Comment by site24x7-old** [comment]
Hi vmpr,

The agent will not be installed again. It is due to the wrong handling of notify blocks . Now we have updated the puppet scripts to provide proper results.

**Comment by site24x7** [comment]
Hello Ringo,                    As per the update from our development team the agent will not be installed again. It is due to the wrong handling of notify blocks . Now we have updated the puppet scripts to provide proper results.Regards,Magesh RajanSite24x7 Team | ZOHO CorpPhone: +1 408 352 9117 | +44 203 564 78934141 Hacienda Dr, Pleasanton, CA 94588, USA---- On Sat, 15 Oct 2016 03:27:19 +0530 support@site24x7.com  wrote ----  Hello Ringo, Thank you for writing to us. We are analyzing this, please give us some more time and will get back to you with an update as soon as possible. Regards,Mohammad Rafee Site24x7 Team | ZOHO CorpUS: +1 408 352 9117 | UK: +44 203 564 78934141 Hacienda Dr, Pleasanton, CA 94588, USASite24x7  | Help Guide | Knowledge Base | Blogs | Forums | DemoIf you have any concerns please mail to escalations@site24x7.comSite24x7 Pre-Meetup Plan - Tell us your Preference---- On Sat, 15 Oct 2016 00:18:28 +0530 notifications@github.com  wrote ---- Hi,   it seems, that this not working:  we have already installed the agent at this moment:  then we execute: puppet agent --test --no-noop  in my opinion, the output says, that it reinstalls the complete environment:  Notice: /Stage[main]/Site24x7::Linuxagent/Exec[remove_tmp_directory]/returns: executed successfully Notice: site24x7 linux monitoring agent installation completed Notice: /Stage[main]/Site24x7/Notify[site24x7 linux monitoring agent installation completed]/message: defined 'message' as 'site24x7 linux monitoring agent installation completed' Notice: Proxy Info  : proxy:3128 Notice: /Stage[main]/Site24x7::Linuxagent/Notify[Proxy Info  : proxy:3128]/message: defined 'message' as 'Proxy Info  : proxy:3128' Notice: File To Download : Site24x7_Linux_64bit.install Notice: /Stage[main]/Site24x7::Linuxagent/Notify[File To Download : Site24x7_Linux_64bit.install]/message: defined 'message' as 'File To Download : Site24x7_Linux_64bit.install' Notice: /Stage[main]/Site24x7::Linuxagent/Exec[Site24x7 Linux Agent]/returns: executed successfully Notice: /Stage[main]/Site24x7::Linuxagent/File[/tmp/site24x7agent/Linux_Agent.install]/mode: mode changed '0644' to '0755' Notice: Succesully Completed Notice: /Stage[main]/Site24x7::Linuxagent/Notify[Succesully Completed]/message: defined 'message' as 'Succesully Completed' Notice: site24x7 linux monitoring agent installation started Notice: /Stage[main]/Site24x7/Notify[site24x7 linux monitoring agent installation started]/message: defined 'message' as 'site24x7 linux monitoring agent installation started' Notice: OS Architecture : x86_64 Notice: /Stage[main]/Site24x7::Linuxagent/Notify[OS Architecture : x86_64]/message: defined 'message' as 'OS Architecture : x86_64' Notice: DEVICE KEY  : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Notice: /Stage[main]/Site24x7::Linuxagent/Notify[DEVICE KEY  : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]/message: defined 'message' as 'DEVICE KEY  : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' Notice: Finished catalog run in 5.41 seconds  Thank you for help! Ringo  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
